stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
      - src/data/data_ingestion.py
      - src/logger
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
      - data/raw
      - src/data/data_preprocessing.py
      - src/logger
    outs:
      - data/interim

  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
      - data/interim
      - src/features/feature_engineering.py
      - src/logger
    params:
      - feature_engineering.max_features
    outs:
      - data/processed
      - models/vectorizer.pkl

  model_building:
    cmd: python -m src.model.model_building
    deps:
      - data/processed
      - src/model/model_building.py
      - src/logger
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python -m src.model.model_evaluation
    deps:
      - models/model.pkl
      - src/model/model_evaluation.py
      - src/logger
    metrics:
      - reports/metrics.json
    outs:
      - reports/experiment_info.json

  model_registration:
    cmd: python -m src.model.register_model
    deps:
      - reports/experiment_info.json
      - src/model/register_model.py
      - src/logger
